fix: 📌 Fixed TypeScript errors by removing unnecessary variable. (#220)
When type checking is performed on the `10_minimum_example/040_vdom_system` sample code, the following error occurs.

```ts
$ pnpm tsc --noEmit --project book/impls/10_minimum_example/040_vdom_system/examples/playground/tsconfig.json
book/impls/10_minimum_example/040_vdom_system/packages/runtime-core/renderer.ts:129:9 - error TS6133: 'n2' is declared but its value is never read.

129     let n2: VNode = null!
        ~~

Found 1 error in book/impls/10_minimum_example/040_vdom_system/packages/runtime-core/renderer.ts:129
```

Therefore, unnecessary variable removed.