fix: 📌Fixed type error "Cannot find module 'rollup/parseAst'" (#242)
As shown below, a type error TS2307 occurs in `vite@5.0.10`.

```sh
$ cd book/impls/10_minimum_example/070_sfc_compiler2
$ pnpm install
$ pnpm tsc --noEmit

../../../../node_modules/.pnpm/vite@5.0.10_@types+node@20.10.5/node_modules/vite/dist/node/index.d.ts:6:41 - error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.

6 export { parseAst, parseAstAsync } from 'rollup/parseAst';
                                          ~~~~~~~~~~~~~~~~~

Found 1 error in ../../../../node_modules/.pnpm/vite@5.0.10_@types+node@20.10.5/node_modules/vite/dist/node/index.d.ts:6
```

Therefore, changed `moduleResolution` to `bundler`.